export const RESOURCE_CREATE_REQUEST = "RESOURCE_CREATE_REQUEST";
export const RESOURCE_CREATE_SUCCESS = "RESOURCE_CREATE_SUCCESS";
export const RESOURCE_CREATE_FAILURE = "RESOURCE_CREATE_FAILURE";

export const RESOURCE_UPDATE_REQUEST = "RESOURCE_UPDATE_REQUEST";
export const RESOURCE_UPDATE_SUCCESS = "RESOURCE_UPDATE_SUCCESS";
export const RESOURCE_UPDATE_FAILURE = "RESOURCE_UPDATE_FAILURE";

export const RESOURCE_DELETE_REQUEST = "RESOURCE_DELETE_REQUEST";
export const RESOURCE_DELETE_SUCCESS = "RESOURCE_DELETE_SUCCESS";
export const RESOURCE_DELETE_FAILURE = "RESOURCE_DELETE_FAILURE";

export const GET_RESOURCES_REQUEST = "GET_RESOURCES_REQUEST";
export const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
export const GET_RESOURCES_FAILURE = "GET_RESOURCES_FAILURE";